version: '3.8'

services:      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    depends_on:
      - nodejsserver
      
  nodejsserver:
    image: my-node-app
    ports:
      - "3000:3000"

networks:
  my_network:
