# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /myapp

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application source code to the container
COPY . .

# Expose the port your Node.js app is listening on
EXPOSE 3000
EXPOSE 3001
EXPOSE 3002

# Define the command to run your Node.js application
CMD ["node", "app.js"]
